### ISSUE TITLE
Regression introduced since version 1.3.1 - Build error

### ISSUE THREAD

**Issue by osieffert** [Phoenix1747/Arduino-Pico-Analog-Correction#2]
A regression has introduce with the commit #9b562cc

The method  ::analogReadTemp(vref) are missing. 

```
.pio/libdeps/pico/PicoAnalogCorrection/PicoAnalogCorrection.cpp: In member function 'float PicoAnalogCorrection::analogReadTemp(pactemp_t)':
.pio/libdeps/pico/PicoAnalogCorrection/PicoAnalogCorrection.cpp:107:17: error: '::analogReadTemp' has not been declared; did you mean 'analogRead'?
  107 |     float t = ::analogReadTemp(_vref);
      |                 ^~~~~~~~~~~~~~
      |                 analogRead
*** [.pio/build/pico/lib614/PicoAnalogCorrection/PicoAnalogCorrection.cpp.o] Error 1

```

Problem when merging PR?

**Comment by NuclearPhoenixx** [comment]
I'm guessing you don't have [arduino-pico](https://github.com/earlephilhower/arduino-pico) installed, right?

**Comment by osieffert** [comment]
I using VSCode editor with platform.io and "Raspberry Pi Pico" arduino library

https://docs.platformio.org/en/latest/boards/raspberrypi/pico.html?utm_source=platformio&utm_medium=piohome

**Comment by NuclearPhoenixx** [comment]
Okay, yes I see. Well, I assumed that everyone using this would be using the Arduino IDE, because I didn't knew that Arduino libraries are also available in platform.io too. Obviously, I was wrong with that assumption.

I can just reverse that change, no problem.

**Comment by NuclearPhoenixx** [comment]
Should be fixed with c0b211f49ff48023fe6b91d21cff7499fc5a8a0e.

It'll probably take some time for the library to get updated.
